name: 'Run Elasticsearch with Plugins'
description: 'Elasticsearch with Plugins'
author: 'miyataka - edited by ppagan-ted'

branding:
  icon: 'database'
  color: 'red'

inputs:
  stack-version:
    description: 'The version of Elasticsearch'
    required: true
  plugins:
    description: 'Elasticsearch plugin strings'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Debug output
      shell: bash
      run: echo running on $HOSTNAME

    - name: Create ES instance
      uses: 'docker'
      image: 'Dockerfile'
      env:
        STACK_VERSION: ${{ inputs.stack-version }}
        PLUGINS: ${{ inputs.plugins }}
