name: Elasticsearch Github Action

on: [push]

jobs:
  run-action:
    name: Start Elasticsearch
    runs-on: self-hosted
    strategy:
      matrix:
        elasticsearch: ["6.4.3", "7.6.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Start Elasticsearch
        uses: ./
        with:
          stack-version: ${{ matrix.elasticsearch }}
          plugins: |
            analysis-kuromoji
            analysis-icu

            #- name: Elasticsearch is reachable
        #run: |
          #curl --verbose --show-error http://localhost:9200
